class PropertiesGenerator
    def initialize(brand_key)
        @brand_key = brand_key
    end

    def generate
        Solara.logger.start_step("Generate brand.properties for Android")
        output_file = FilePath.android_generated_properties
        content = "# Generated by Solara\n"

        load_config.each do |key, value|
            content << "#{key}=#{value}\n"
        end

        File.write(output_file, content)
        Solara.logger.debug("🎉 Generated properties file: #{output_file}, content below ⬇️")
        Solara.logger.debug("--------------\n#{content}--------------")
        Solara.logger.end_step("Generate brand.properties for Android")
    end

    def load_config
        config_path = FilePath.android_brand_config(@brand_key)
        signing_path = FilePath.brand_signing(@brand_key, Platform::Android)
        config = JSON.parse(File.read(config_path))
        signing_config = JSON.parse(File.read(signing_path))

        config.merge!(signing_config)

        config
      end
end